name: CI Backend

on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: ./backend
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20-bookworm-slim
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

      - name: Run Prettier
        run: npm run prettier

      - name: Run Lint
        run: npm run lint
