@startuml SPA Components
!include <C4/C4_Component>

Person(businessAdmin, "Administrator")

Container_Boundary(spa, "SPA", "React") {
  Component(dshPage, "Dashboard", "Page")

  Component(navMenu, "Navigation Menu", "Component")

  Boundary(inventory, "Inventory") {
    Component(inventoryPage, "Inventory", "Page")
    Component(createProductModal, "Create Product", "Modal")
    Component(modifyStockProductModal, "Modify Stock", "Modal")
  }

  Boundary(sales, "Sales") {
    Component(salesPage, "Sales", "Page")
    Component(createSaleModal, "Create Sale", "Modal")
  }

  Boundary(transactions, "Transactions") {
    Component(transactionsPage, "Transactions", "Page")
    Component(createTransactionModal, "Create Transaction", "Modal")
  }
}

Rel(businessAdmin, spa, "Navigate on")
Rel(dshPage, navMenu, "Uses")
Rel(inventoryPage, navMenu, "Uses")
Rel(salesPage, navMenu, "Uses")
Rel(transactionsPage, navMenu, "Uses")
Rel(navMenu, inventoryPage, "Navigate to", "Link")
Rel(navMenu, salesPage, "Navigate to", "Link")
Rel(navMenu, transactionsPage, "Navigate to", "Link")
Rel(inventoryPage, createProductModal, "Open")
Rel(inventoryPage, modifyStockProductModal, "Open")
Rel(salesPage, createSaleModal, "Open")
Rel(transactionsPage, createTransactionModal, "Open")

@enduml
