' components/spa.puml
@startuml SPA Components
!include <C4/C4_Component>

Person(businessAdmin, "Administrator")

Container_Boundary(spa, "SPA", "React") {
  Component(dshPage, "Dashboard", "Page")

  Component(navMenu, "Navigation Menu", "Component")
  Component(quickActions, "Quick Actions", "Component")

  Boundary(inventory, "Inventory") {
    Component(inventoryPage, "Inventory", "Page")
    Component(newProductAcquisitionSideForm, "New Product Acquisition", "SideForm")
  }

  Boundary(sales, "Sales") {
    Component(salesPage, "Sales", "Page")
    Component(createSaleSideForm, "New Sale", "Side Form")
  }

  Boundary(transactions, "Transactions") {
    Component(transactionsPage, "Transactions", "Page")
    Component(newSpentSideForm, "New Spent", "SideForm")
  }

  Boundary(metrics, "Metrics")
}

Rel(businessAdmin, spa, "Navigate on")
Rel(dshPage, navMenu, "Uses")
Rel(dshPage, quickActions, "Uses")
Rel(inventoryPage, navMenu, "Uses")
Rel(salesPage, navMenu, "Uses")
Rel(transactionsPage, navMenu, "Uses")
Rel(navMenu, inventoryPage, "Navigate to", "Link")
Rel(navMenu, salesPage, "Navigate to", "Link")
Rel(navMenu, transactionsPage, "Navigate to", "Link")
Rel(inventoryPage, newProductAcquisitionSideForm, "Open")
Rel(salesPage, createSaleSideForm, "Open")
Rel(transactionsPage, newSpentSideForm, "Open")
Rel(quickActions, newProductAcquisitionSideForm, "Open")
Rel(quickActions, createSaleSideForm, "Open")
Rel(quickActions, newSpentSideForm, "Open")
Rel(dshPage, metrics, "Show")

@enduml
